package numbersense.exam;

/**
 * @author George Chen
 * @since 8/5/12 8:25 PM
 */

public enum Category {
	NOT_A_TRICK,
	BASE_CONVERSION,
	DIVISIBILITY,
	PRIME_NUMBER,
	ROMAN_NUMERAL,
	ARABIC_TO_ROMAN,
	ORDER_OF_OPERATION,
	SQUARE,
	CUBE,

	MULTIPLICATION_FOIL,
	MULTIPLICATION_SLIGHTLY_LESS_THAN_100,
	MULTIPLICATION_BY_11,
	MULTIPLICATION_BY_12,
	MULTIPLICATION_BY_101,
	MULTIPLICATION_BY_5,
	MULTIPLICATION_BY_50,
	MULTIPLICATION_BY_25,
	MULTIPLICATION_BY_125,
	MULTIPLICATION_SLIGHTLY_GREATER_THAN_100
}
