package numbersense.exam;

/**
 * @author George Chen
 * @since 8/5/12 8:25 PM
 */

public enum Category {
	NOT_A_TRICK,

	DIVISIBILITY,
	PRIME_NUMBER,
	ROMAN_NUMERAL,
	ARABIC_TO_ROMAN,
	ORDER_OF_OPERATION,
	SQUARE,
	CUBE,

	FACTORIAL,

	MULTIPLICATION_FOIL,
	MULTIPLICATION_SLIGHTLY_LESS_THAN_100,
	MULTIPLICATION_BY_11,
	MULTIPLICATION_BY_12,
	MULTIPLICATION_BY_101,
	MULTIPLICATION_BY_5,
	MULTIPLICATION_BY_50,
	MULTIPLICATION_BY_25,
	MULTIPLICATION_BY_125,
	GCD,
	SQUARE_NUMBER_ENDING_IN_5,
	MULTIPLICATION_BY_NUMBER_BETWEEN_12_AND_19,
	BASE_2_AND_4,
	MULTIPLICATION_SLIGHTLY_GREATER_THAN_100
}
